apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crypto-gaf.componentName" (dict "root" . "component" "schema") }}
  labels:
    {{- include "crypto-gaf.labels" . | nindent 4 }}
data:
  schema.sql: |-
    CREATE SCHEMA IF NOT EXISTS crypto_gaf;

    CREATE TABLE IF NOT EXISTS crypto_gaf.gafs
    (
      buy_image text,
      orderbook_image text,
      max_size integer,
      midpoint numeric,
      midpoint_images text[],
      product text PRIMARY KEY NOT NULL,
      sell_image text,
      size integer
    );

    CREATE TABLE IF NOT EXISTS crypto_gaf.samples
    (
      ask_prices numeric[],
      ask_sizes numeric[],
      bid_prices numeric[],
      bid_sizes numeric[],
      buys numeric[],
      midpoint numeric,
      product text references crypto_gaf.gafs(product),
      sample_id bigserial PRIMARY KEY,
      sells numeric[]
    );

    {{- range .Values.api.products }}
    INSERT INTO crypto_gaf.gafs (product, max_size)
      VALUES ('{{ .name }}', {{ default 600 .maxSize }})
      ON CONFLICT (product) DO NOTHING;
    {{- end }}
