version: '2'
services:
  coinbase-local:
    build: coinbase-local
    image: cgaf-infra_coinbase-local
    environment:
      PRODUCTS: BTC-USD
  pg:
    build: pg
    image: cgaf-infra_pg
networks:
  default:
    external:
      name: cgaf
