version: '3.7'
services:
  collect:
    build: collect
    image: cgaf-datasource_collect
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      SLEEP_INTERVAL: 0.25
    secrets:
      - pg_pw
  calculate:
    build: calculate
    image: cgaf-datasource_calculate
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      SLEEP_INTERVAL: 0.5
    secrets:
      - pg_pw
secrets:
  pg_pw:
    file: ./pg_pw.txt
networks:
  default:
    external:
      name: cgaf
